### Get all lessons
GET http://localhost:8000/api/lesson?lessonsPerPage=10 HTTP/1.1

### Get all filtered lessons
GET http://localhost:8000/api/lesson?teachersIds=1 HTTP/1.1

### Create lessons with firstDate and lastDate
POST http://localhost:8000/api/lesson HTTP/1.1
Content-Type: application/json

{
  "teacherIds": [2, 4],
  "title": "Andromache",
  "days": [0,1,2],
  "firstDate": "2019-09-13",
  "lastDate": "2019-09-24"
}

### Create lessons with firstDate and lessonsCount
POST http://localhost:8000/api/lesson HTTP/1.1
Content-Type: application/json

{
  "teacherIds": [2, 4],
  "title": "impala",
  "days": [0,1,2],
  "firstDate": "2019-09-12",
  "lessonsCount": 10
}

